### ISSUE TITLE
`@mui/lab` not included?

### ISSUE THREAD

**Issue by FahriDevZ** [kajirikajiri/eslint-plugin-mui-path-imports#12]
I think `@mui/lab` should be added because lab package is part of mui

**Comment by kajirikajiri** [comment]
I think it is within the scope of the package, considering the name of the package, so I will try to respond to it.

**Comment by kajirikajiri** [comment]
Thank you @FahriDevZ !
Supported @mui/lab with this pr.

https://github.com/kajirikajiri/eslint-plugin-mui-path-imports/pull/13
