### ISSUE TITLE
Support for Joy? 

### ISSUE THREAD

**Issue by bailout00** [kajirikajiri/eslint-plugin-mui-path-imports#21]
Joy is still early but I'm wondering if you have any thoughts on supporting it?

**Comment by kajirikajiri** [comment]
I think @mui/joy should be supported because it is related to mui. However, it is currently not supported. If I have time on Saturday or Sunday, I will try to support it.

**Comment by kajirikajiri** [comment]
Thank you @bailout00 !
Supported @mui/joy.

https://github.com/kajirikajiri/eslint-plugin-mui-path-imports/releases/tag/v0.0.8
